name: Loja-PHP Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Loja Laravel Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Instalação do Composer
      - uses: ./.github/actions/composer

      # Instalação do Laravel
      - uses: ./.github/actions/config-laravel

      # Execução dos testes
      - run: ./vendor/bin/phpunit
